### ISSUE TITLE
upgraded to 1.1.0, undefined local variable or method `currency_value_class_info'

### ISSUE THREAD

**Issue by jberhang** [code-mancers/invoicing#74]
Upgrading from 1.0.1 to 1.1.0 yields this error:

```
/Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activerecord-5.1.7/lib/active_record/dynamic_matchers.rb:22:in `method_missing': undefined local variable or method `currency_value_class_info' for #<Class:0x007f9c29b22088> (NameError)
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted.rb:306:in `method_missing'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/attr_encrypted-3.1.0/lib/attr_encrypted/adapters/active_record.rb:131:in `method_missing_with_attr_encrypted'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/invoicing-1.1.0/lib/invoicing/currency_value.rb:122:in `block in <module:CurrencyValue>'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.7/lib/active_support/concern.rb:120:in `class_eval'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/activesupport-5.1.7/lib/active_support/concern.rb:120:in `append_features'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/invoicing-1.1.0/lib/invoicing/class_info.rb:75:in `include'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/invoicing-1.1.0/lib/invoicing/class_info.rb:75:in `acts_as'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/invoicing-1.1.0/lib/invoicing/currency_value.rb:116:in `acts_as_currency_value'
	from /Users/justin/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/invoicing-1.1.0/lib/invoicing/ledger_item.rb:315:in `acts_as_ledger_item'
```

**Comment by thegeorgeous** [comment]
Same as #66
